# frozen_string_literal: true

source 'https://rubygems.org'

# gem "rails"

gem 'ruby_wasm', '~> 2.6'

# gem 'sinatra', '~> 4.0'

# gem 'rackup', '~> 2.1'

# gem 'rubocop', '~> 1.63', group: :development

gem "slim", "~> 5.2"

gem "js", "~> 2.6"
